export const AppMetadataKeys = {
  APP_CONTROLLERS: Symbol('app:controllers'),
  APP_MODEL: Symbol('app:model'),
  APP_PROVIDER: Symbol('app:provider'),
  BINDING_TYPE: Symbol('binding:type'),
  CONTROLLER_METADATA: Symbol('controller:metadata'),
  CONTROLLER_METHOD_METADATA: Symbol('controller:method:metadata'),
  CONTAINER_MODULE: Symbol('container:module'),
  CONTROLLER_PARAM: Symbol('controller:param'),
  HTTP_STATUS: Symbol('http:status'),
  IS_MODULE: Symbol('is:module'),
  IS_PUBLIC: Symbol('is:public'),
  MAIN_CONTAINER: Symbol('main:container'),
  MODULE_EXPORTS: Symbol('module:exports'),
  MODULE_IMPORTS: Symbol('module:imports'),
  SLS_HANDLERS: Symbol('sls:handlers'),
} as const;
